services:
  - type: web
    name: amigurumis
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: REPO_OWNER
        scope: run_and_build
      - key: REPO_NAME
        scope: run_and_build
